image: archlinux/base

stages:
    - build

build:
    stage: build
    before_script:
        - pacman -Sy --noconfirm 
        - pacman -S python python-pip --noconfirm 
        - pip install Pillow
        - pip install numpy
        - pip install pycryptodome 
    script:
        - python -m py_compile Image-Steganography.py 

